export enum BusinessSector {
  Fashion = "Fashion",
  Electronics = "Electronics",
  Gadgets = "Gadgets",
  Home_Decoration_Garden = "Home /Decoration/ Garden",
  Beauty_Personal_Care = "Beauty & Personal Care",
  Health_Wellness = "Health & Wellness",
  Sports_Outdoors = "Sports & Outdoors",
  Automotive = "Automotive",
  Food_Beverage = "Food & Beverage",
  Baby_Kids = "Baby & Kids",
  Pet_Supplies = "Pet Supplies",
  Office_Supplies = "Office Supplies",
  Books = "Books",
  Industrial_Scientific = "Industrial & Scientific",
  Toys_Games = "Toys & Games",
  FMCG_Supermarket = "FMCG/Supermarket",
}
